apiVersion: v1
kind: Secret
metadata:
  name: food-secrets
  namespace: food
type: Opaque
data:
  ADMIN_NAME: YWRtaW4=                        # admin
  ADMIN_EMAIL: YWRtaW5AdGVzdC5jb20=          # admin@test.com
  ADMIN_PASSWORD: MTIzNDU2Nzg=               # 12345678
  JWT_SECRET: SzNqITlzRCM4bFEybVZ4Wg==

  MONGO_INITDB_ROOT_USERNAME: cm9vdA==        # root
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ==    # example
  MONGO_DB_NAME: bnZhbGFkREI=                 # nvaladDB

  BACKEND_PORT: NTAwMA==                      # 5000
  FRONTEND_PORT: MzAwMA==                     # 3000
  ADMIN_PORT: MzAwMQ==                        # 3001
  NODE_ENV: ZGV2ZWxvcG1lbnQ=                  # development

  MONGO_URI: bW9uZ29kYjovL3Jvb3Q6ZXhhbXBsZUBtb25nb2RiOjI3MDE3L252YWxhZERCP2F1dGhTb3VyY2U9YWRtaW4=
