apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  ADMIN_NAME: {{ .Values.secrets.adminName | b64enc }}
  ADMIN_EMAIL: {{ .Values.secrets.adminEmail | b64enc }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | b64enc }}
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.secrets.mongoUser | b64enc }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.mongoPassword | b64enc }}
  MONGO_DB_NAME: {{ .Values.secrets.mongoDbName | b64enc }}
  BACKEND_PORT: {{ .Values.backend.port | b64enc }}
  FRONTEND_PORT: {{ .Values.frontend.port | b64enc }}
  ADMIN_PORT: {{ .Values.admin.port | b64enc }}
  NODE_ENV: {{ .Values.nodeEnv | b64enc }}
  MONGO_URI: {{ .Values.secrets.mongoUri | b64enc }}
